### ISSUE TITLE
1.10.50; Fucking Bethesda fucking patching for no fucking reason fuck

### ISSUE THREAD

**Issue by Baddest-Juju** [StochasticTinkr/PerformanceTuner#5]
TIME FOR EVERYTHING TO BE BROKEN AGAIN, THANKS BETHESDA

https://bethesda.net/community/topic/149/fallout-4-game-updates/6

IT DOES NOTHING HAHAHAHA

**Comment by StochasticTinkr** [comment]
Sorry to hear that.  I'm actually on a business trip right now and don't have access to my machine...  You can help though!  If you download Cheat Engine, and use it to find the new addresses, that would make it easy for me to update it as soon as I'm back.

        const unsigned __int64 offset_fShadowDirDistance = 0x676BA1C;
	const unsigned __int64 offset_iVolumetricQuality = 0x3903FD8;
	const unsigned __int64 offset_bGameUpdatePaused = 0x5AA50E4;
	const unsigned __int64 offset_bIsMainMenu = 0x5B473A8;
	const unsigned __int64 offset_bIsLoading = 0x5A9D300;

These are the ones I use.  If you save a cheat-engine file, I'll be able to use that to update these values.

**Comment by Baddest-Juju** [comment]
I could probably do that. When do you get back?

**Comment by Baddest-Juju** [comment]
Okay, after mucking about with Cheat Engine for about half an hour, I've come to the conclusion I don't really know what I'm doing. I could probably get fShadowDirDistance by setting it to a strange number. And assuming the latter 3 are all just true/false switches, I could probably get those by going back and forth with next scan until I'm left with only one address. No idea how I'd grab iVolumetricQuality though. I feel like I must be missing something.

I did try the 'string' search but that didn't do any good.

**Comment by thericeking** [comment]
I hope you are always around to fix this mod every time Bethesda breaks it with an update. I'm nowhere near done playing this game and I got it on the day it was released. I think there will be people playing this game for many more years just like there are people still playing Skyrim.

**Comment by bmanzzs** [comment]
Fellas, stop worrying. Just rollback using these steps. It works, just did it.
https://www.reddit.com/r/Fallout/comments/7gh1c4/patch_11050_released_how_to_roll_back_your/

**Comment by thericeking** [comment]
@bmanzzs I appreciate the temporary solution but the new patch does (supposedly) fixes bugs and improves performance so it's a good thing. We still need this mod updated. I wish I knew more about programing so I could contribute but I'm working on that.

**Comment by Baddest-Juju** [comment]
@StochasticTinkr Could you share some insight as to how to accurately capture the new values with Cheat Engine? I understand the basics now, but everything I've been reading is predicated on narrowing results down from changing values. Even if my previous reply has the right idea, it still doesn't explain how iVolumetricQuality is captured.

...actually, just as I was typing this, I realized I could probably narrow that down by changing the value via console command. Hmm!

Something that would really help is some sort of way to ensure Fallout 4 stays active. Whenever you tab away it pauses, which might affect something in a negative way. And I'm not entirely sure if bGameUpdatePaused = pause menu or not...

**Comment by StochasticTinkr** [comment]
The way I did it with CE is this:  Set the ShadowDirDistance to some arbitrary number (like 3657), and do a scan for that number.  Then I quit the game, set the shadow distance to a different arbitrary number (eg 7651), and do a second scan for that number.  That narrowed it down to two memory locations, though you may find more.   

While in the game, I used cheat engine to change the value at one of those locations, and if it didn't work, I tried the other.

For the iVolumetricQuality,  I did use console command to do what you're talking about.

As for the "game update paused" and "loading", they were  a little harder.   I configured fallout4 to not automatically pause when I left the game (I forget the setting name, Bilago's Configuration Tool has it).  Then I searched for 0 when the game was running normally, and 1 for when it was paused, and again for 0 when it was running normally, etc...  I had to do this a bunch, and it only narrowed it down to 17 locations.  Some of which weren't in FO4, but in other dlls, so I ignored those.  I found one location that looked like it had the a count that included pipboy and/or console and/or container open and/or lockpick and/or escape menu...  So I chose that location. 

For the "loading" location, I searched for "1" when the game was on the loading, then 0 when it was normal play, then fast-travelled and searched for 1 again, etc... This also didn't get it down to one obvious choice, but any of them seemed to work for the cases I wanted...

I have noticed that leaving caves didn't activate the "Load Accelerator" behavior, which probably means I need to test with that one too. 

What I think I'm going to do is actually move these memory locations into an INI file, so that people can update the INI without me needing to recompile for every FO4 update.  This would also make it compatible with more versions of FO4.

**Comment by StochasticTinkr** [comment]
Oh, I should note, ShadowDirDistance is a "Float" in CE, and everything else was an int (4 byte)

**Comment by Madpaddy** [comment]
Please update appreciate you doing this thank you.

**Comment by StochasticTinkr** [comment]
This is fixed in the 0.9.2 release.  You'll need to make sure to download the addresses ini file(s).  Do not rename them.

**Comment by Madpaddy** [comment]
Thanks for the updates, great job.
